# Nome da Actions:
name: Snake Game

# Quando a Action será executada
on:
  schedule:
    # Atualiza a cada 1 hora
    - cron: "0 */1 * * *"
  # Permite execução manual via botão no GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Faz o checkout do repositório
      - uses: actions/checkout@v3

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: G4brielAndrade
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Configura Git para poder dar commit, se necessário
      - name: Config Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Mostra o status do repositório (debug)
      - run: git status

      # Faz push das mudanças geradas
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos da pasta dist na branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
